### ISSUE TITLE
site is giving a 404 

### ISSUE THREAD

**Issue by myrajurek** [FRC2713/QRScout#15]
https://qr-scout.vercel.app/ and https://scout.redhawkrobotics.org/ are giving a 404
![image](https://github.com/FRC2713/QRScout/assets/80414217/723c2194-c630-45ab-abdc-006251287f72)

**Comment by tytremblay** [comment]
We changed to github pages.  Please use https://frc2713.github.io/QRScout/  until we redirect http://scout.redhawkrobotics.org

**Comment by myrajurek** [comment]
can you update the link here 
![image](https://github.com/FRC2713/QRScout/assets/80414217/4560db1f-4606-44db-b021-be77761fa019)

**Comment by tytremblay** [comment]
Good catch.  Fixed!
