### ISSUE TITLE
how

### ISSUE THREAD

**Issue by AntonioScott123** [FRC2713/QRScout#22]
stop gatekeeping please and tell me how to setup it up.... Thanks!

**Comment by rbgk** [comment]
It's not graciously professional to baselessly claim Ty is purposely gatekeeping this project. 
The code is fully open source, and anyone with the skillset required, would know where to start. 
Try saying, "I'm confused on how to get started. Can I get some help with set up?" See how different the tone and energy is? 


It is unclear as to what you do and do not know, and it makes it harder for others to help you effectively. 
Where are you in the process? What have you done? How familiar are you with this repository's codebase?

**Comment by AntonioScott123** [comment]
My bad I did not mean it like that but it's fine because I don't need it anymore
