### ISSUE TITLE
Persistent Component - Causing Problems

### ISSUE THREAD

**Issue by noahlinton** [FRC2713/QRScout#9]
When uploading a custom json configuration, one component from the original configuration persists, but does not work, and when interacted with, it resets the configuration. 

The persistent component is "upper Cube/Cone Missed" which is the second component in the auto section. 

This component does not exists in our custom configuration, but is showing up on the webpage, and when we click on it, suddenly the configuration resets, but the component does not work. 

<img width="657" alt="image" src="https://user-images.githubusercontent.com/19657478/221334062-c65ef888-8157-41a3-af37-8d0048688009.png">

**Comment by allengregoryiv** [comment]
This is happening for us as well.

**Comment by tytremblay** [comment]
Taking a look!

**Comment by tytremblay** [comment]
Could one of you upload your config file for me to test with?

**Comment by allengregoryiv** [comment]
https://drive.google.com/file/d/1E3th62ELcriYDH4F61FJYv-jKrTFVCti/view?usp=drivesdk

**Comment by tytremblay** [comment]
This should be fixed once vercel picks up the changes from #10 .  Also added dark mode which will be picked up automatically if your OS is set to dark mode.

**Comment by tytremblay** [comment]
actually, ill let one of you confirm and close.

**Comment by noahlinton** [comment]
Resolved for us! Thank you very much! Excited to use this again this year!
